spring.application.name=smartcampus

# Server
server.port=8083

# MySQL (update password!)
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_db
spring.datasource.username=root
spring.datasource.password=Dinna@2003

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JWT (dev/demo)
app.jwt.secret=change_me_to_a_long_random_secret
app.jwt.issuer=smartcampus

# Logging
logging.level.com.smartcampus=DEBUG

