# MySQL profile (docker-compose/local MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus_db
spring.datasource.username=smartuser
spring.datasource.password=S3cur3P@ss

spring.jpa.hibernate.ddl-auto=update
